[CmdletBinding()]
param()

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

$ProjectRoot = Split-Path -Parent $PSScriptRoot
$PythonExe = Join-Path $ProjectRoot ".venv\Scripts\python.exe"
$SpecPath = Join-Path $ProjectRoot "UniversalTranscoder.spec"
$InstallerScript = Join-Path $ProjectRoot "installer\UniversalTranscoder.iss"
$BuildDir = Join-Path $ProjectRoot "build"
$DistDir = Join-Path $ProjectRoot "dist"
$VersionInfoPath = Join-Path $BuildDir "windows_version_info.txt"

function Assert-FileExists {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Path,
        [Parameter(Mandatory = $true)]
        [string]$Label
    )

    if (-not (Test-Path -LiteralPath $Path)) {
        throw "$Label not found: $Path"
    }
}

function Invoke-PythonInline {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Script,
        [Parameter(Mandatory = $true)]
        [string]$ErrorMessage
    )

    $Script | & $PythonExe -
    if ($LASTEXITCODE -ne 0) {
        throw $ErrorMessage
    }
}

function Get-IsccPath {
    $fromPath = Get-Command iscc.exe -ErrorAction SilentlyContinue
    if ($fromPath) {
        return $fromPath.Source
    }

    $candidates = @(
        (Join-Path $env:LOCALAPPDATA "Programs\Inno Setup 6\ISCC.exe"),
        (Join-Path ${env:ProgramFiles(x86)} "Inno Setup 6\ISCC.exe"),
        (Join-Path $env:ProgramFiles "Inno Setup 6\ISCC.exe")
    )

    foreach ($candidate in $candidates) {
        if ($candidate -and (Test-Path -LiteralPath $candidate)) {
            return $candidate
        }
    }

    return $null
}

Assert-FileExists -Path $PythonExe -Label "Python executable"
Assert-FileExists -Path $SpecPath -Label "PyInstaller spec"
Assert-FileExists -Path $InstallerScript -Label "Inno Setup script"
Assert-FileExists -Path (Join-Path $ProjectRoot "bin\ffmpeg.exe") -Label "FFmpeg binary"
Assert-FileExists -Path (Join-Path $ProjectRoot "bin\ffprobe.exe") -Label "FFprobe binary"

Push-Location $ProjectRoot
try {
    & $PythonExe -c "import PyInstaller, polib"
    if ($LASTEXITCODE -ne 0) {
        throw "Required build dependencies are missing. Install PyInstaller and polib in the virtual environment."
    }

    $metadataJson = & $PythonExe -c "import json; from core.app_info import APP_EXE_NAME, APP_EXECUTABLE_FILENAME, APP_ID, APP_INSTALLER_BASENAME, APP_INSTALL_DIRNAME, APP_NAME, APP_PUBLISHER, APP_VERSION, APP_VERSION_WIN; print(json.dumps({'APP_EXE_NAME': APP_EXE_NAME, 'APP_EXECUTABLE_FILENAME': APP_EXECUTABLE_FILENAME, 'APP_ID': APP_ID, 'APP_INSTALLER_BASENAME': APP_INSTALLER_BASENAME, 'APP_INSTALL_DIRNAME': APP_INSTALL_DIRNAME, 'APP_NAME': APP_NAME, 'APP_PUBLISHER': APP_PUBLISHER, 'APP_VERSION': APP_VERSION, 'APP_VERSION_WIN': APP_VERSION_WIN}))"
    if ($LASTEXITCODE -ne 0) {
        throw "Unable to load application metadata from core.app_info."
    }
    $metadata = $metadataJson | ConvertFrom-Json
    $innoAppId = $metadata.APP_ID -replace "^\{", "{{"

    Write-Host "Compiling translation catalogs..."
    $compileTranslationsScript = @"
from pathlib import Path
import polib

project_root = Path(r"$ProjectRoot")
compiled = []
for po_path in sorted(project_root.glob("locales/*/LC_MESSAGES/*.po")):
    mo_path = po_path.with_suffix(".mo")
    po = polib.pofile(po_path)
    po.save_as_mofile(mo_path)
    compiled.append((po_path, mo_path))

if not compiled:
    raise SystemExit("No translation catalogs found.")

for source_path, output_path in compiled:
    print(f"Compiled {source_path} -> {output_path}")
"@
    Invoke-PythonInline -Script $compileTranslationsScript -ErrorMessage "Translation compilation failed."

    if (Test-Path -LiteralPath $BuildDir) {
        Remove-Item -LiteralPath $BuildDir -Recurse -Force
    }
    if (Test-Path -LiteralPath $DistDir) {
        Remove-Item -LiteralPath $DistDir -Recurse -Force
    }
    New-Item -ItemType Directory -Path $BuildDir | Out-Null

    Write-Host "Generating Windows version resource..."
    $versionInfoScript = @"
from pathlib import Path
from core.app_info import (
    APP_EXE_NAME,
    APP_EXECUTABLE_FILENAME,
    APP_NAME,
    APP_PUBLISHER,
    APP_VERSION,
    APP_VERSION_WIN,
)

version_tuple = tuple(int(part) for part in APP_VERSION_WIN.split("."))
version_text = f'''# UTF-8
#
# Auto-generated by scripts/build_release.ps1
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={version_tuple},
    prodvers={version_tuple},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable(
        '040904B0',
        [
          StringStruct('CompanyName', '{APP_PUBLISHER}'),
          StringStruct('FileDescription', '{APP_NAME}'),
          StringStruct('FileVersion', '{APP_VERSION_WIN}'),
          StringStruct('InternalName', '{APP_EXE_NAME}'),
          StringStruct('OriginalFilename', '{APP_EXECUTABLE_FILENAME}'),
          StringStruct('ProductName', '{APP_NAME}'),
          StringStruct('ProductVersion', '{APP_VERSION}')
        ]
      )
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
'''

output_path = Path(r"$VersionInfoPath")
output_path.write_text(version_text, encoding="utf-8")
print(output_path)
"@
    Invoke-PythonInline -Script $versionInfoScript -ErrorMessage "Unable to generate the Windows version resource."

    $env:UT_VERSION_FILE = $VersionInfoPath
    try {
        Write-Host "Building dist\UniversalTranscoder.exe with PyInstaller..."
        & $PythonExe -m PyInstaller --clean --noconfirm $SpecPath
        if ($LASTEXITCODE -ne 0) {
            throw "PyInstaller build failed."
        }
    }
    finally {
        Remove-Item Env:UT_VERSION_FILE -ErrorAction SilentlyContinue
    }

    $distExePath = Join-Path $DistDir $metadata.APP_EXECUTABLE_FILENAME
    Assert-FileExists -Path $distExePath -Label "Built executable"
    Write-Host "Executable built: $distExePath"

    $isccPath = Get-IsccPath
    if (-not $isccPath) {
        throw "Inno Setup Compiler (ISCC.exe) was not found. Install Inno Setup 6 and rerun the script. The application executable was built successfully: $distExePath"
    }

    Write-Host "Building installer with Inno Setup..."
    & $isccPath `
        "/DAppName=$($metadata.APP_NAME)" `
        "/DAppVersion=$($metadata.APP_VERSION)" `
        "/DAppExeName=$($metadata.APP_EXECUTABLE_FILENAME)" `
        "/DAppOutputBaseFilename=$($metadata.APP_INSTALLER_BASENAME)-$($metadata.APP_VERSION)" `
        "/DAppId=$innoAppId" `
        "/DAppInstallDirName=$($metadata.APP_INSTALL_DIRNAME)" `
        "/DAppPublisher=$($metadata.APP_PUBLISHER)" `
        $InstallerScript
    if ($LASTEXITCODE -ne 0) {
        throw "Inno Setup build failed."
    }

    $installerPath = Join-Path $DistDir "$($metadata.APP_INSTALLER_BASENAME)-$($metadata.APP_VERSION).exe"
    Assert-FileExists -Path $installerPath -Label "Built installer"
    Write-Host "Installer built: $installerPath"
}
finally {
    Pop-Location
}
